name: Meshery Security Scans

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: false
        default: 'main'
      components:
        description: 'Select components to scan (comma-separated or "all")'
        required: false
        default: 'all'

jobs:
  setup-tools:
    name: Setup Security Tools
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b . v0.105.0
          sudo mv syft /usr/local/bin/syft

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b . v0.78.0
          sudo mv grype /usr/local/bin/grype

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          install-only: true

      - name: Install OpenVEX
        run: |
          curl -LO https://github.com/openvex/openvex/releases/latest/download/openvex-linux-amd64
          chmod +x openvex-linux-amd64
          sudo mv openvex-linux-amd64 /usr/local/bin/openvex

  scan-components:
    name: Scan Component - ${{ matrix.component }}
    runs-on: ubuntu-latest
    needs: setup-tools
    strategy:
      matrix:
        component: ["meshery", "mesheryctl", "meshery-ui", "provider"]
        include:
          - component: meshery
            path: ./server
          - component: mesheryctl
            path: ./mesheryctl
          - component: meshery-ui
            path: ./ui
          - component: provider
            path: ./provider-ui

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Build Docker image
        if: ${{ github.event.inputs.components == 'all' || contains(github.event.inputs.components, matrix.component) }}
        run: |
          cd ${{ matrix.path }}
          docker build -t ${{ matrix.component }}:latest .

      - name: Trivy Image Scan
        if: ${{ github.event.inputs.components == 'all' || contains(github.event.inputs.components, matrix.component) }}
        id: trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ matrix.component }}:latest
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

      - name: Show Trivy Scan Summary
        if: ${{ github.event.inputs.components == 'all' || contains(github.event.inputs.components, matrix.component) }}
        run: |
          echo "Trivy scan for ${{ matrix.component }}:"
          cat trivy-results.sarif || echo "No SARIF output found."

      - name: Generate SBOM with Syft
        if: ${{ github.event.inputs.components == 'all' || contains(github.event.inputs.components, matrix.component) }}
        run: |
          cd ${{ matrix.path }}
          syft . -o cyclonedx-json > ../../${{ matrix.component }}-sbom.json

      - name: Upload SBOM Artifact
        if: ${{ github.event.inputs.components == 'all' || contains(github.event.inputs.components, matrix.component) }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.component }}-sbom
          path: ${{ matrix.component }}-sbom.json

      - name: Grype SBOM Scan (VEX Report)
        if: ${{ github.event.inputs.components == 'all' || contains(github.event.inputs.components, matrix.component) }}
        run: |
          grype sbom:../../${{ matrix.component }}-sbom.json -o cyclonedx-json > ../../${{ matrix.component }}-grype-vex.json

      - name: Show Grype VEX Summary
        if: ${{ github.event.inputs.components == 'all' || contains(github.event.inputs.components, matrix.component) }}
        run: |
          echo "Grype VEX for ${{ matrix.component }}:"
          head -20 ../../${{ matrix.component }}-grype-vex.json

      - name: Upload Grype VEX Artifact
        if: ${{ github.event.inputs.components == 'all' || contains(github.event.inputs.components, matrix.component) }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.component }}-grype-vex
          path: ${{ matrix.component }}-grype-vex.json

      - name: OpenVEX from SBOM
        if: ${{ github.event.inputs.components == 'all' || contains(github.event.inputs.components, matrix.component) }}
        run: |
          openvex generate --sbom ../../${{ matrix.component }}-sbom.json --output ../../${{ matrix.component }}-openvex.json

      - name: Show OpenVEX Summary
        if: ${{ github.event.inputs.components == 'all' || contains(github.event.inputs.components, matrix.component) }}
        run: |
          echo "OpenVEX for ${{ matrix.component }}:"
          head -20 ../../${{ matrix.component }}-openvex.json

      - name: Upload OpenVEX Artifact
        if: ${{ github.event.inputs.components == 'all' || contains(github.event.inputs.components, matrix.component) }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.component }}-openvex
          path: ${{ matrix.component }}-openvex.json
