name: Security Tools Comparison

on:
  push:
    branches: [main] # or [main, develop, ...] for more branches
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: false
        default: 'main'

jobs:
  trivy-scan:
    name: Trivy SCA & Image Scan & SBOM
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' || github.ref == format('refs/heads/{0}', github.event.inputs.branch)
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}
      - name: Trivy FS Scan (SCA)
        run: trivy fs --format table .
      - name: Trivy Image Scan
        run: |
          docker build -t testimage:latest .
          trivy image --format table testimage:latest
      - name: Trivy SBOM (CycloneDX)
        run: trivy sbom --format cyclonedx --output trivy-sbom.json .

  grype-scan:
    name: Grype SCA & SBOM
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' || github.ref == format('refs/heads/{0}', github.event.inputs.branch)
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}
      - name: Grype FS Scan (SCA)
        run: grype dir:.
      - name: Build Docker Image
        run: docker build -t testimage:latest .
      - name: Grype Image Scan
        run: grype testimage:latest
      - name: Generate SBOM with Syft
        run: syft dir:. -o cyclonedx-json > syft-sbom.json
      - name: Grype SBOM Scan
        run: grype sbom:syft-sbom.json

  cyclonedx-sbom:
    name: CycloneDX SBOM Generation
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' || github.ref == format('refs/heads/{0}', github.event.inputs.branch)
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}
      - name: Generate CycloneDX SBOM (Node.js example)
        run: |
          npm install -g @cyclonedx/bom
          cyclonedx-bom -o cyclonedx-sbom.json

  openvex-report:
    name: OpenVEX VEX Reporting
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' || github.ref == format('refs/heads/{0}', github.event.inputs.branch)
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}
      - name: Generate SBOM with Syft
        run: syft dir:. -o cyclonedx-json > syft-sbom.json
      - name: Generate VEX with OpenVEX
        run: |
          curl -LO https://github.com/openvex/openvex/releases/latest/download/openvex-linux-amd64
          chmod +x openvex-linux-amd64
          ./openvex-linux-amd64 generate --sbom syft-sbom.json --output openvex.json

  snyk-scan:
    name: Snyk SCA
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' || github.ref == format('refs/heads/{0}', github.event.inputs.branch)
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}
      - name: Snyk Auth
        run: snyk auth ${{ secrets.SNYK_CODE }}
      - name: Snyk Test
        run: snyk test
      - name: Snyk SBOM
        run: snyk sbom --format=cyclonedx1.4+json > snyk-sbom.json

  semgrep-sast:
    name: Semgrep SAST
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' || github.ref == format('refs/heads/{0}', github.event.inputs.branch)
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1

  gitleaks-secrets:
    name: Gitleaks Secrets Scan
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' || github.ref == format('refs/heads/{0}', github.event.inputs.branch)
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

  trufflehog-secrets:
    name: TruffleHog Secrets Scan
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' || github.ref == format('refs/heads/{0}', github.event.inputs.branch)
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}
      - name: Run TruffleHog
        run: |
          pip install trufflehog
          trufflehog filesystem .
