name: Security Tools Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  trivy-fs-scan:
    name: Trivy FS Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Trivy FileSystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  trivy-image-scan:
    name: Trivy Image Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t testimage:latest .

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          scan-ref: 'testimage:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  grype-scan:
    name: Grype FS & Image Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Grype FS Scan
        uses: anchore/scan-action@v3
        with:
          path: .

      - name: Build Docker Image
        run: docker build -t testimage:latest .

      - name: Run Grype Image Scan
        uses: anchore/scan-action@v3
        with:
          image: testimage:latest

  syft-sbom:
    name: Generate SBOM with Syft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate SBOM (CycloneDX)
        uses: anchore/sbom-action@v0.15.1
        with:
          path: .
          output-file: sbom.spdx.json

  snyk-scan:
    name: Snyk Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Test
        uses: snyk/actions/node@v1
        with:
          command: test

      - name: Generate SBOM
        run: snyk sbom --format=cyclonedx1.4+json > snyk-sbom.json

  semgrep-sast:
    name: Semgrep Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: 'auto'

  gitleaks-secrets:
    name: Gitleaks Secrets Detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "detect --source=. --verbose"

  trufflehog-secrets:
    name: TruffleHog Secrets Detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3
        with:
          scanArguments: "filesystem ."
